blank_issues_enabled: false
contact_links:
  - name: ğŸŒˆ ç¤¾åŒºäº¤æµ
    url: https://github.com/oliver-xie666/sonic-music/discussions
    about: åŠ å…¥æˆ‘ä»¬çš„ç¤¾åŒºè¿›è¡Œäº¤æµå’Œè®¨è®º
  - name: ğŸ“š é¡¹ç›®æ–‡æ¡£
    url: https://github.com/oliver-xie666/sonic-music
    about: æŸ¥çœ‹é¡¹ç›®æ–‡æ¡£ä»¥è·å–æ›´å¤šå¸®åŠ©ä¿¡æ¯
  - name: ğŸ› ï¸ å¼€å‘ä¸ç¼–è¯‘
    url: https://github.com/oliver-xie666/sonic-music#readme
    about: äº†è§£é¡¹ç›®å¦‚ä½•è¿›è¡Œå¼€å‘å’Œç¼–è¯‘
